<?php

/**
 * @file
 * Contains calendar_hours_server.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function calendar_hours_server_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the hours module.
    case 'help.page.calendar_hours_server':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Connect to Google Calendar API') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_cron().
 */
function calendar_hours_server_cron() {
  /** @var \Drupal\calendar_hours_server\Entity\HoursCalendarStorage $calendarStorage */
  $calendarStorage = \Drupal::service('entity_type.manager')->getStorage('hours_calendar');
  $tagsToInvalidate = [];
  foreach ($calendarStorage->loadMultiple() as $calendar) {
    $tagsToInvalidate[] = 'calendar_hours_' . $calendar->id;
  }

  /** @var \Drupal\Core\Cache\CacheTagsInvalidator $invalidator */
  $invalidator = \Drupal::service('cache_tags.invalidator');
  $invalidator->invalidateTags($tagsToInvalidate);
}


